sudo: required
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - hexo # build master branch only
install:
  - npm install
script:
  - hexo clean
  - hexo g -d # generate static files