sudo: required
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - hexo # build master branch only
install:
  - npm install
script:
  - hexo clean
  - hexo g -d # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  target_branch: master