sudo: required
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - hexo # build master branch only
install:
  - npm install
script:
  - hexo clean
after_success:
  - sed -i s/token_github/$GH_TOKEN/g _config.yml
  - hexo deploy